#<-----------------------------Deploy deployment with k8s------------------->
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: elasticsearch-client
  labels:
    es-name: elasticsearch
    role: client
spec:
  serviceName: elasticsearch-client
  replicas: 2
  template:
    metadata:
      labels:
        es-name: elasticsearch
        role: client
    spec:
      nodeSelector:
        service_type: public
      # Use the stork scheduler to enable more efficient placement of the pods
      initContainers:
      - name: init-sysctl
        image: busybox
        imagePullPolicy: IfNotPresent
        command: ["sysctl", "-w", "vm.max_map_count=262144"]
        securityContext:
          privileged: true
      containers:
      - name: elasticsearch-client
        securityContext:
          privileged: false
          capabilities:
            add:
              - IPC_LOCK
              - SYS_RESOURCE
        image: quay.io/pires/docker-elasticsearch-kubernetes:6.3.2
        imagePullPolicy: Always
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: "CLUSTER_NAME"
          value: "es-cluster"
        - name: NODE_MASTER
          value: "false"
        - name: NODE_DATA
          value: "false"
        - name: HTTP_ENABLE
          value: "true"
        - name: "ES_JAVA_OPTS"
          value: "-Xms512m -Xmx512m"
        ports:
        - containerPort: 9300
          name: transport
          protocol: TCP
        - containerPort: 9200
          name: http
          protocol: TCP
        volumeMounts:
        - name: es-storage
          mountPath: /data
      volumes:
        - name: storage
          emptyDir:
          medium: ""

#<-----------------------------Deploy service with k8s------------------->
apiVersion: v1
kind: Service
metadata:
  name: client-elasticsearch-service
  labels:
    es-name: elasticsearch
    role: client
spec:
  selector:
    es-name: elasticsearch
    role: client
  ports:
  - name: http
    port: 9200
    protocol: TCP
