# ------------------- Deployment ------------------- #
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: elk-es-service
  namespace: public-service
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      service: elk-es-service
  template:
    metadata:
      labels:
        service: elk-es-service
    spec:
      nodeSelector:
        kubernetes.io/hostname: worker-k8s-n03
      containers:
      - name: es-service
        image: registry-mirror.mo9.com/public-service/elasticsearch:v5.6.2
        imagePullPolicy: Always
        resources:
          limits:
            memory: 1024Mi
          requests:
            cpu: 300m
            memory: 300Mi
        ports:
          - containerPort: 9200
        env:
          - name: network.host
            value: "0.0.0.0"
          - name: node.name
            value: "${HOSTNAME}"
          - name: discovery.zen.ping.unicast.hosts
            value: "127.0.0.1:9300"
          - name: cluster.name
            value: "elk-single"
          - name: ES_JAVA_OPTS
            value: "-Xms512m -Xmx512m"
        volumeMounts:
          - name: es-single-data
            mountPath: /usr/share/elasticsearch/data
      volumes:
          - name: es-single-data
            emptyDir: {}
---
# ------------------- Dashboard Service ------------------- #

kind: Service
apiVersion: v1
metadata:
  name: config-service
  labels:
    service: config-service
  namespace: public-service
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 8401
  selector:
      service: config-service
