#<-----------------------------Deploy deployment with k8s------------------->
apiVersion: apps/v1beta1
kind: Deployments
metadata:
  name: elasticsearch-master
  labels:
    es-name: elasticsearch
    role: master
  namespace: public-service
spec:
  serviceName: es-master
  replicas: 3
  selector:
    matchLabels:
      es-name: elasticsearch
      role: master
  template:
    metadata:
      labels:
        es-name: elasticsearch
        role: master
    spec:
      nodeSelector:
        service_type: public
      # Use the stork scheduler to enable more efficient placement of the pods
      initContainers:
      - name: init-sysctl
        image: registry-mirror.mo9.com/public-service/busybox:v1.0
        imagePullPolicy: IfNotPresent
        command: ["sysctl", "-w", "vm.max_map_count=262144"]
        securityContext:
          privileged: true
      containers:
      - name: elasticsearch-master
        securityContext:
          privileged: true
          capabilities:
            add:
              - IPC_LOCK
              - SYS_RESOURCE
        image: registry-mirror.mo9.com/public-service/elasticsearch:6.3.2 
        imagePullPolicy: Always
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: "CLUSTER_NAME"
          value: "es-cluster"
        - name: "NUMBER_OF_MASTERS"
          value: "2"
        - name: NODE_MASTER
          value: "true"
        - name: NODE_INGEST
          value: "false"
        - name: NODE_DATA
          value: "false"
        - name: HTTP_ENABLE
          value: "false"
        - name: "ES_JAVA_OPTS"
          value: "-Xms512m -Xmx512m"
        ports:
        - containerPort: 9300
          name: transport
          protocol: TCP
        volumeMounts:
        - name: es-storage
          mountPath: /data
      volumes:
        - name: es-storage
          hostPath:
            path: /data/apps/es-data/
#<-----------------------------Deploy service with k8s------------------->
apiVersion: v1
kind: Service
metadata:
  name: master-elasticsearch-service
  labels:
    es-name: elasticsearch
    role: master
spec:
  selector:
    es-name: elasticsearch
    role: master
  ports:
  - name: transport
    port: 9300
    protocol: TCP
