# ------------------- Deployment ------------------- #
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx-service
  namespace: public-service
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      service-name: Tengine-2.2.3
  template:
    metadata:
      labels:
        service-name: Tengine-2.2.3
    spec:
      nodeSelector:
        kubernetes.io/hostname: worker-k8s-n01
      hostNetwork: true
      containers:
      - name: nginx
        image: registry-mirror.mo9.com/library/tengine:v2.2.3
        resources:
          limits:
            memory: 300Mi
          requests:
            cpu: 30m
            memory: 30Mi
        ports:
        - name: http
          containerPort: 80
        - name: https
          containerPort: 443
        readinessProbe:
          tcpSocket:
            port: 443
          initialDelaySeconds: 30
          timeoutSeconds: 30
        volumeMounts:
          - name: conf-dir
            mountPath: /etc/nginx
            readOnly: false
          - name: logs-dir
            mountPath: /var/log/nginx
            readOnly: false
      volumes:
        - name: conf-dir
          hostPath:
            path: /etc/nginx
        - name: logs-dir
          hostPath:
            path: /var/log/nginx
